Cypress.Commands.add('login', (username, password) => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.visit("http://zero.webappsecurity.com/login.html")
    cy.get('#user_login').type(username)
    cy.get('#user_password').type(password)
    cy.contains('Sign in').click()
})

Cypress.Commands.add('payBills', (payee, account, amount, date, description) => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.login("username", "password")
    cy.visit("http://zero.webappsecurity.com/bank/pay-bills.html")
    cy.get('#sp_payee').select(payee)
    cy.get('#sp_account').select(account)
    cy.get('#sp_amount').type(amount)
    cy.get('#sp_description').type(description)
    cy.get('#sp_date').type(date)
})
